---
- name: Create a file using Ansible
  hosts: all
  tasks:
    - name: Ensure directory exists
      ansible.builtin.file:
        path: "/home/ubuntu"
        state: directory

    - name: Create a file
      ansible.builtin.file:
        path: "/home/ubuntu/sample.txt"
        state: touch
