# site.yml

- name: Install and configure Nginx
  hosts: all
  become: yes
  roles:
    - nginx_role

- name: Deploy hello page
  hosts: all
  tasks:
    - name: Ensure index.html exists
      copy:
        content: "Hello from Ansible!\n"
        dest: /usr/share/nginx/html/index.html
      become: yes
