- name: Install and configure Apache
  hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Add message to Apache index.html
      lineinfile:
        path: /usr/share/apache2/default-site/htdocs/index.html
        line: "hello ansible github actions"

    - name: Restart Apache
      systemd:
        name: apache2
        state: restarted

  roles:
    - geerlingguy.apache
