name: Server Provisioning

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: "Enter Main/HSM Server IP"
        required: true
      username:
        description: "Enter the username to use for provisioning"
        required: true

jobs:
  provision_server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Ansible Playbook
        run: |
          mkdir -p ~/.ansible
          echo "[targets]" > ~/.ansible/hosts
          echo "${{ github.event.inputs.server_ip }}" ansible_user=${{ github.event.inputs.username }} >> ~/.ansible/hosts
          /usr/local/bin/ansible-playbook site.yml --inventory ~/.ansible/hosts --key-file .ansible_key
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"
          ANSIBLE_DEPRECATION_WARNINGS: "false"
          ANSIBLE_DEBUG: "1"
