# name: Ping Server

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: "Enter Server IP"
        required: true

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v5
        with:
          playbook: |
            ---
            - name: Ping server
              hosts: all
              tasks:
                - name: Ping server
                  ping:
          inventory: ${{ github.event.inputs.server_ip }},
          key: ${{ secrets.EC2_INSTANCE_PEM_FILE }}
          user: ubuntu
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"
          ANSIBLE_DEPRECATION_WARNINGS: "false"
